# configuration for small GPU
run_name: base-fp32

model:
  n_layer: 6
  n_head: 6
  n_embd: 384
  block_size: 256

train:
  batch_size: 64
  max_steps: 2000
  max_lr: 1.0e-3
  dtype: float32
  compile: false
  eval_interval: 100
  eval_iters: 40
  eval_batch_size: 64
  seed: 1337
  device: cuda
  mode: online

data:
  path: data/input.txt